version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: discord.js
    versions:
    - 12.5.2
  - dependency-name: minecraft-server-util
    versions:
    - 3.4.4
  - dependency-name: discord.js-commando
    versions:
    - 0.12.2
